version: '3.8'

services:
  dream-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=5000
      - MYSQL_HOST=mysql
      - MYSQL_USER=dream_bot
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=dream_bot_db
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_ADMIN_USER_ID=${LINE_ADMIN_USER_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
      - LOG_LEVEL=INFO
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - dream-bot-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=dream_bot_db
      - MYSQL_USER=dream_bot
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - dream-bot-network

volumes:
  mysql_data:

networks:
  dream-bot-network:
    driver: bridge